num_epochs: 100000
batch_size: 512
learning_rate: 0.0003
concept_size: 1
num_concept: 3
f_size: 64
decoder: conv
num_missing: [1, 2]
seed: 60

embed_size: 16
embed_hidden: [32]
aggregator_hidden: [256, 256]
func_hidden: [128, 128]
func_param_hidden: [128]
aggregator_size: 128

anneal:
  beta_z:
    value: [200.0, 200.0]
    milestones: [0, 1000]
    mode: continuous
  beta_f:
    value: [50.0, 50.0]
    milestones: [0, 1000]
    mode: continuous
  x_sigma:
    value: [0.1, 0.1]
    milestones: [0, 100]
    mode: continuous
  z_sigma:
    value: [0.1, 0.1]
    milestones: [0, 100]
    mode: continuous
  beta_mi:
    value: [5000.0, 5000.0]
    milestones: [0, 100]
    mode: continuous
