num_epochs: 100000
batch_size: 512
learning_rate: 0.0003
concept_size: 1
num_concept: 7
f_size: 64
decoder: deep_conv
num_missing: [1, 4]
seed: 0

embed_size: 16
embed_hidden: [32]
aggregator_hidden: [128, 128]
func_hidden: [128]
func_param_hidden: [64]
aggregator_size: 64

anneal:
  beta_z:
    value: [0.0, 50.0]
    milestones: [0, 400]
    mode: continuous
  beta_f:
    value: [0.0, 50.0]
    milestones: [0, 400]
    mode: continuous
  x_sigma:
    value: [0.1, 0.1]
    milestones: [0, 100]
    mode: continuous
  z_sigma:
    value: [0.03, 0.03]
    milestones: [0, 100]
    mode: continuous
  beta_mi:
    value: [150.0, 150.0]
    milestones: [0, 1000]
    mode: continuous
